# action.yml
name: 'Python GHTest'
description: 'Greet someone and record the time'
inputs:
  var1:  # id of input
    description: 'Passing in a variable'
    required: true
    default: 'my var number 1'
  var2:
    description: 'Variable that isn"t required'
    required: false
  im_a_bool:
    description: 'testing how booleans are converted to python'
# outputs:
#  time: # id of output
#    description: 'The time we greeted you'
#  files:
#    description: 'ls command'
runs:
  using: "composite"
    steps:
      - name: Run action
        run: python3 action.py
        env:
          INPUT_VAR1: ${{ inputs.VAR1 }}
          INPUT_VAR2: ${{ inputs.VAR2 }}
          INPUT_IM_A_BOOL: ${{ inputs.IM_A_BOOL  }}
        shell: bash
    # args:
    #- ${{ inputs.who-to-greet }}
