# action.yml
name: 'Python GHTest'
description: 'Greet someone and record the time'
inputs:
  var1:  # id of input
    description: 'Passing in a variable'
    required: true
    default: 'my var number 1'
# outputs:
#  time: # id of output
#    description: 'The time we greeted you'
#  files:
#    description: 'ls command'
runs:
  using: 'docker'
  image: 'Dockerfile'
    # args:
    #- ${{ inputs.who-to-greet }}
