name: Test

on: [push] [pull request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: TechWiz-3/python-gh-action@master
        #with:
        #  files: test.md
        #  blacklist:  https://www.github.com/paramt/this-doesnt-exist
