name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        # username/repo@branch/versiontag
        uses: TechWiz-3/python-gh-action@non-docker
        # variables you want to pass in - accessed as env variables - INPUT_<VAR_NAME_HERE>
        with:  # passing in env variables defined in the action.yml file
          im_a_bool: true
          # this variable is now set in the docker environment as INPUT_IM_A_BOOL
        env:  # passing in env variables not defined in the action.yml file
          PASSWD: ${{ secrets.SECRET_PASSWD }}
