name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        # username/repo@branch/versiontag
        uses: TechWiz-3/python-gh-action@main
        # variables you want to pass in - accessed as env variables - INPUT_<VAR_NAME_HERE>
        with:  # passing in env variables defined in the action files
          im_a_bool: true
          # this variable is set in the environment as INPUT_IM_A_BOOL
          test: "ayo"
